In [1]:
import pandas as pd
import numpy as np

In [2]:
dates = pd.date_range("20130101", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -1.857813  2.490184 -0.522920  0.573196
2013-01-02 -0.293856 -0.154430 -0.477630  0.643790
2013-01-03 -1.590673 -0.632128 -1.470176  1.997080
2013-01-04 -1.120520  0.707534  0.628678 -0.081264
2013-01-05  0.178870  0.408173  0.770604  2.547970
2013-01-06 -1.257943 -0.094589 -0.252682  0.471869

In [5]:
df[2:4]

                   A         B         C         D
2013-01-03 -1.590673 -0.632128 -1.470176  1.997080
2013-01-04 -1.120520  0.707534  0.628678 -0.081264

For label slicing, both endpoints are included:

In [3]:
df["20130102":"20130104"]

                   A         B         C         D
2013-01-02 -0.293856 -0.154430 -0.477630  0.643790
2013-01-03 -1.590673 -0.632128 -1.470176  1.997080
2013-01-04 -1.120520  0.707534  0.628678 -0.081264

In [7]:
df.iloc[3]

A   -1.120520
B    0.707534
C    0.628678
D   -0.081264
Name: 2013-01-04 00:00:00, dtype: float64

In [8]:
df[df > 0]

                  A         B         C         D
2013-01-01      NaN  2.490184       NaN  0.573196
2013-01-02      NaN       NaN       NaN  0.643790
2013-01-03      NaN       NaN       NaN  1.997080
2013-01-04      NaN  0.707534  0.628678       NaN
2013-01-05  0.17887  0.408173  0.770604  2.547970
2013-01-06      NaN       NaN       NaN  0.471869

In [9]:
serie1 = pd.Series(list(range(1,7)), index=pd.date_range("20130102", periods=6))
df["F"] = serie1
df

                   A         B         C         D    F
2013-01-01 -1.857813  2.490184 -0.522920  0.573196  NaN
2013-01-02 -0.293856 -0.154430 -0.477630  0.643790  1.0
2013-01-03 -1.590673 -0.632128 -1.470176  1.997080  2.0
2013-01-04 -1.120520  0.707534  0.628678 -0.081264  3.0
2013-01-05  0.178870  0.408173  0.770604  2.547970  4.0
2013-01-06 -1.257943 -0.094589 -0.252682  0.471869  5.0

In [10]:
len(df)

6

In [11]:
df.shape

(6, 5)

In [12]:
df.size

30

In [13]:
df

                   A         B         C         D    F
2013-01-01 -1.857813  2.490184 -0.522920  0.573196  NaN
2013-01-02 -0.293856 -0.154430 -0.477630  0.643790  1.0
2013-01-03 -1.590673 -0.632128 -1.470176  1.997080  2.0
2013-01-04 -1.120520  0.707534  0.628678 -0.081264  3.0
2013-01-05  0.178870  0.408173  0.770604  2.547970  4.0
2013-01-06 -1.257943 -0.094589 -0.252682  0.471869  5.0

In [14]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])

In [15]:
df1

                   A         B         C         D    F   E
2013-01-01 -1.857813  2.490184 -0.522920  0.573196  NaN NaN
2013-01-02 -0.293856 -0.154430 -0.477630  0.643790  1.0 NaN
2013-01-03 -1.590673 -0.632128 -1.470176  1.997080  2.0 NaN
2013-01-04 -1.120520  0.707534  0.628678 -0.081264  3.0 NaN

In [18]:
df1[["B", "A"]]

                   B         A
2013-01-01  2.490184 -1.857813
2013-01-02 -0.154430 -0.293856
2013-01-03 -0.632128 -1.590673
2013-01-04  0.707534 -1.120520